import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaTruck } from "react-icons/fa";
import { MdBlockFlipped } from "react-icons/md";
import { SiGoogledocs } from "react-icons/si";
import { FaGraduationCap } from "react-icons/fa";
import { FaUser } from "react-icons/fa";
import { BsRCircle } from "react-icons/bs";
import { FaRegPenToSquare } from "react-icons/fa6";
import { IoIosArrowDown } from "react-icons/io";
import { FaFile } from "react-icons/fa";
import { RxCrossCircled } from "react-icons/rx";
import { FaClock } from "react-icons/fa";

export default function Dashboardbody() {
  const navigate = useNavigate();
  const [eactive, setEactive] = useState(false);
  return (
    <div className="dashboardbody">
      <div className={eactive? "side-bar active" : "side-bar"}>
        <div onClick={()=>setEactive(!eactive)}>
          <div>
            <FaTruck />
          </div>
          <p>e-Waybill</p>
          <IoIosArrowDown
            style={{ marginRight: "0", marginLeft: "auto", marginTop: "4px" }}
          />
        </div>
        {eactive?(
          <>
            <span className="sub-content">
          <div>
            <p onClick={()=>navigate('/dashboard/new')}>Generate New</p>
          </div>
          <div>
            <p>Generate Bulk</p>
          </div>
          <div>
            <p>Update Part B/Vehicle</p>
          </div>
          <div>
            <p>Update Vehicle-Bulk</p>
          </div>
          <div>
            <p>Change to Multivehicle</p>
          </div>
          <div>
            <p>Extend validity</p>
          </div>
          <div>
            <p>Update EWB Transporter</p>
          </div>
          <div>
            <p>Update EWB Trans.Bulk</p>
          </div>
          <div>
            <p>Cancel</p>
          </div>
          <div>
            <p>Print EWB</p>
          </div>
        </span>
          </>
        ):('')}
        <div>
          <div>
            <MdBlockFlipped />
          </div>
          <p>Reject</p>
        </div>
        <div>
          <div>
            <SiGoogledocs />
          </div>
          <p>Reports</p>
        </div>
        <div>
          <div>
            <FaGraduationCap />
          </div>
          <p>My Masters</p>
        </div>
        <div>
          <div>
            <FaUser />
          </div>
          <p>User Management</p>
        </div>
        <div>
          <div>
            <BsRCircle />
          </div>
          <p>Registration</p>
        </div>
        <div>
          <div>
            <FaRegPenToSquare />
          </div>
          <p>Update</p>
        </div>
      </div>
      <div className="main-content">
        <div className="main-content-header">Dash Board for Last 7 Days</div>
        <div className="box-container">
          <div className="box" style={{ backgroundColor: "#34985c" }}>
            <p className="box-heading" style={{ backgroundColor: "#318652", fontSize: "14px" }}>
              <FaFile fontSize={'17px'}/> EWBs generated by me
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
          <div className="box" style={{ backgroundColor: "#6964ab" }}>
            <p className="box-heading" style={{ backgroundColor: "#5d5897" }}>
              <RxCrossCircled fontSize={'17px'}/> EWBs cancelled by me
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
          <div className="box" style={{ backgroundColor: "#b9853a" }}>
            <p className="box-heading" style={{ backgroundColor: "#a46812" }}>
              <MdBlockFlipped fontSize={'17px'}/> EWBs rejected by me
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
          <div className="box" style={{ backgroundColor: "#ac4a41" }}>
            <p className="box-heading" style={{ backgroundColor: "#99423a" }}>
              <FaFile/> EWBs Gen. by other party on my GSTIN
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
          <div className="box" style={{ backgroundColor: "#1eaee0" }}>
            <p className="box-heading" style={{ backgroundColor: "#1d9ac6" }}>
              <MdBlockFlipped fontSize={'17px'}/> My EWBs rejected by other party
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
          <div className="box" style={{ backgroundColor: "#9a9494" }}>
            <p className="box-heading" style={{ backgroundColor: "#8c8a8b" }}>
              <FaClock/> EWB pending for part-B updation
            </p>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
            <div className="box-element">
              <div>13/02/2023</div>
              <div>0</div>
            </div>
          </div>
        </div>
        <div className="latest-updates">
          <div
            style={{
              width: "90%",
              height: "70%",
              display: "grid",          
            }}
          >
            <div style={{ width: "65%", height: "90%" }}>
              <div style={{color: "#559ac7", fontSize: "21px", fontWeight: "600", fontStyle: "italic"}}>Latest Updates</div>
              <hr />
              <div
                style={{
                  fontSize: "12px",
                  color: "red",
                  margin: "5px",
                  marginLeft: "0",
                }}
              >
                Enhancements in E-Way Bills System
              </div>
              <div style={{ color: "grey", fontSize: "15px" }}>
                1. Single sign-on (SSO) is a facility by which the user can
                login to the e-ay bills system using his/her credentials and
                click on the e-Invoice link to access e-Invoice system directly
                ithout logging again and vice versa.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
